<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0OHGDCN" ignored="0" name="TestInChrome" tests="4" failures="1" timestamp="07 Feb 2023 15:58:48 GMT" time="34.872" errors="0">
  <testcase name="Login" time="5.725" classname="assignment11.TestNg_Assignment10"/>
  <testcase name="CreateCourse" time="12.638" classname="assignment11.TestNg_Assignment10"/>
  <testcase name="Delete" time="10.189" classname="assignment11.TestNg_Assignment10">
    <failure type="java.lang.AssertionError" message="expected not same [3] but found [3]">
      <![CDATA[java.lang.AssertionError: expected not same [3] but found [3]
at assignment11.TestNg_Assignment10.Delete(TestNg_Assignment10.java:151)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Delete -->
  <testcase name="tearDown" time="0.812" classname="assignment11.TestNg_Assignment10"/>
</testsuite> <!-- TestInChrome -->
